### ISSUE TITLE
Do not start webcam upon mouse hover

### ISSUE THREAD

**Issue by ahmetalpbalkan** [thieman/github-selfies#56] opened 2015-04-15 20:09 UTC
Anytime I hover the extension's buttons (which apparently I mistakenly do 20 times a day because my mouse pointer happens to pass over it) it starts webcam immediately. Sort of like UX bug to me since it's annoying and I rarely take selfies. :)

Not sure if it's happening to just me.

![image](https://cloud.githubusercontent.com/assets/159209/7168205/7c93199c-e370-11e4-9346-1b99e0901ee1.png)

**Comment by thieman** [comment] 2015-04-15 20:40
Thanks for writing in! I think we've already got an issue covering this, however, so I'm going to close this one and direct you there.

Duplicate of #53

**Closed by thieman** 2015-04-15 20:40 UTC
