### ISSUE TITLE
Wait until mouse click before starting webcam stream

### ISSUE THREAD

**Issue by iandees** [thieman/github-selfies#59] opened 2015-07-06 18:25 UTC
I find myself accidentally triggering the Github selfie button on mouseover by scrolling down the Github issue page with my mouse in the right spot. It would be great if the plugin would display the buttons but wait until the user clicked on them before requesting access to and displaying the stream of the webcam.

**Comment by thieman** [comment] 2015-07-06 19:30
+1

I think this is a dupe of #53 which was closed for some reason. I've reopened #53 and will close this one.

**Closed by thieman** 2015-07-06 19:30 UTC

**Comment by iandees** [comment] 2015-07-06 20:01
Thanks!
